### PR TITLE
Update values to use new format

### PR DESCRIPTION
**Pull request by pereztr5**

### CODE REVIEW

**Review by JAORMX — CHANGES_REQUESTED** [review]
@pereztr5 you'll need to re-update the helm chart, as it was reverted in another commit.

**Comment by pereztr5** [comment]
I'm not following what needs to be re-updated?

**Comment by JAORMX** [comment]
@pereztr5 I thought we were trying to update to fuse `1.2.6`

**Comment by pereztr5** [comment]
I see, so this is using the new `1.2.6` [chart](https://github.com/equinixmetal-helm/k8s-mergestat/blob/main/Chart.yaml#L8). Renovate actually took care of that in this PR https://github.com/equinixmetal-helm/k8s-mergestat/pull/11.

But I see that now we are using the `latest` container image vs a specific version. Asking Patrick if they will be tagging their containers with the version so we can pin it.

**Comment by pereztr5** [comment]
Okay setup so they use the the specific tag. They don't have versioned tags yet until it's out of alpha it seems like.

**Review by JAORMX — APPROVED** [review]

**Pull request merged**
